### PR TITLE
Specify jsonc 

### PR DESCRIPTION
**Pull request by bamurtaugh**
Specify devcontainer.json as jsonc.

### CODE REVIEW

**Review by greggroth — APPROVED** [review]
Thanks!

**Review by Chuxel — APPROVED** [review]

**Comment by chrmarti** [comment]
What are the reasons to disallow trailing commas? (Looking at https://github.com/microsoft/vscode/pull/146957.)

**Comment by greggroth** [comment]
JSON C isn't exactly a spec and not all editors will tolerate trailing commas like VS Code does. Additionally, libraries for JSON C support comments, but no additional features like trailing commas ([example](https://github.com/muhammadmuzzammil1998/jsonc))

See this discussion for more about it: https://github.com/microsoft/vscode/issues/102061

**Comment by chrmarti** [comment]
Makes sense. Merging the PR, thanks @greggroth!

**Pull request merged**
